# Generated by Django 5.1.2 on 2024-11-04 06:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=155, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=155, unique=True)),
                ('image', models.ImageField(default='imag/user-default-image', upload_to='agent_images')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_1', models.EmailField(blank=True, max_length=50, null=True)),
                ('skype', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agentlar',
            },
        ),
    ]
