# Generated by Django 5.1.2 on 2024-11-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='img/user-default-image', upload_to='agent_images'),
        ),
    ]
