# Generated by Django 5.1.2 on 2024-11-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=models.SlugField(blank=True, max_length=155, null=True, unique=True),
        ),
    ]
