# Generated by Django 5.1.2 on 2024-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_agent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
