# Generated by Django 5.1.2 on 2024-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_agentcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontact',
            name='name',
            field=models.CharField(default=0, max_length=155),
            preserve_default=False,
        ),
    ]
