# Generated by Django 5.1.2 on 2024-11-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_image'),
        ('contact', '0003_agentcontact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcontact',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AgentContact', to='agent.agent'),
        ),
    ]
