# Generated by Django 5.1.2 on 2024-11-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqimizda', 'verbose_name_plural': 'Haqimizda'},
        ),
    ]
