# Generated by Django 5.1.2 on 2024-11-04 05:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('male_name', models.CharField(max_length=100)),
                ('female_name', models.CharField(max_length=100)),
                ('testimonial', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(default='img/default-image.jpg', upload_to='testimonials/')),
            ],
            options={
                'verbose_name': 'Guvohnoma',
                'verbose_name_plural': 'Guvohnomalar',
            },
        ),
    ]
