# Generated by Django 5.1.2 on 2024-11-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'verbose_name': 'Asosiy Model',
                'verbose_name_plural': 'Asosiy Modellar',
                'abstract': False,
            },
        ),
    ]
