# Generated by Django 5.1.2 on 2024-11-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_company_country_link_country_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Kompaniya', 'verbose_name_plural': 'Kompaniyalar'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Mamlakat', 'verbose_name_plural': 'Mamlakatlar'},
        ),
    ]
