# Generated by Django 5.1.2 on 2024-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_testimonial_likes_testimonial_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(default=0, upload_to='testimonial_videos'),
            preserve_default=False,
        ),
    ]
