# Generated by Django 5.1.2 on 2024-11-04 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agent_likes_agent_views'),
        ('article', '0008_article_likes_comment_likes_comment_views'),
        ('common', '0007_testimonial_video'),
        ('eCommerce', '0005_property_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'EmailObuna',
                'verbose_name_plural': 'EmailObunalar',
            },
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_agent', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=('Like', 'Like'), max_length=15)),
                ('liked_article', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=('Like', 'Like'), max_length=15)),
                ('liked_comment', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=('Like', 'Like'), max_length=15)),
                ('liked_testimonial', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=('Like', 'Like'), max_length=15)),
                ('liked_property', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=('Like', 'Like'), max_length=15)),
                ('liked_user', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=('Like', 'Like'), max_length=15)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_agent', to='agent.agent')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_article', to='article.article')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment', to='article.comment')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_from_user', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_property', to='eCommerce.property')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_testimonial', to='common.testimonial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yoqtirish',
                'verbose_name_plural': 'Yoqtirishlar',
            },
        ),
    ]
