# Generated by Django 5.1.2 on 2024-11-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_subscribe_email_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe_email',
            name='sub_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
