# Generated by Django 5.1.2 on 2024-11-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': 'HashTag', 'verbose_name_plural': 'HashTaglar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
    ]
