# Generated by Django 5.1.2 on 2024-11-04 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='testimonial_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
