# Generated by Django 5.1.2 on 2024-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_description_1_article_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(default=0, upload_to='article_videos'),
            preserve_default=False,
        ),
    ]
