# Generated by Django 5.1.2 on 2024-11-04 12:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_alter_property_options_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(default=0, upload_to='property_videos'),
            preserve_default=False,
        ),
    ]
