# Generated by Django 5.1.2 on 2024-11-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0004_propertycategory_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
