# Generated by Django 5.1.2 on 2024-11-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0007_property_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='img/default-image.jpg', upload_to='property_images/'),
        ),
    ]
